database:
  host: localhost
  port: 5432
  name: olist
  schema: public
paths:
  data_dir: data
  customers: data/olist_customers_dataset.csv
  geolocation: data/olist_geolocation_dataset.csv
  order_items: data/olist_order_items_dataset.csv
  order_payments: data/olist_order_payments_dataset.csv
  order_reviews: data/olist_order_reviews_dataset.csv
  orders: data/olist_orders_dataset.csv
  products: data/olist_products_dataset.csv
  sellers: data/olist_sellers_dataset.csv
  category_translation: data/product_category_name_translation.csv